on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@HEAD
    - run: |
        docker login -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}} ghcr.io
        docker build -t ghcr.io/${{github.repository}} .
        docker push ghcr.io/${{github.repository}}
